### ISSUE TITLE
Error with webtrees 2.0

### ISSUE THREAD

**Issue by Fa10175** [UksusoFF/webtrees-tree_view_full_screen#1]
I try your module with webtrees 2.0 and i have this error:

> Fatal error: Declaration of UksusoFF\WebtreesModules\TreeViewFullScreen\TreeViewFullScreen::defaultMenuOrder() must be compatible with Fisharebest\Webtrees\Module\ModuleMenuInterface::defaultMenuOrder(): int in ...........\htdocs\webtrees\modules_v4\webtrees-tree_view_full_screen\module.php on line 13

Thanks for any solution

**Comment by UksusoFF** [comment]
@Fa10175 
I still on 1.7 branch. 2.0 version released yesterday. I will update own install and check this issue.

**Comment by UksusoFF** [comment]
@Fa10175
Please check [0.3 version](https://github.com/UksusoFF/webtrees-tree_view_full_screen/releases/tag/0.3).

**Comment by Fa10175** [comment]
I try 0.3 version.
it 's ok for me no error and it do his job
 thanks

**Comment by Fa10175** [comment]
do you try to update "Webtrees - Face" also?
let's me know, i can tested also if you need.
Thanks and good job

Le lun. 9 déc. 2019 à 14:41, Kirill Uksusov <notifications@github.com> a
écrit :

**Comment by UksusoFF** [comment]
Yep, but Faces have many logic with database. Now inspecting how it's implemented in wt 2.0.
I will update it asap.

**Comment by UksusoFF** [comment]
@Fa10175 please check new version: https://github.com/UksusoFF/webtrees-faces
And [create new issue](https://github.com/UksusoFF/webtrees-faces/issues/new) if any troubles with it.
