### ISSUE TITLE
Module not working on individual page, works on chart page

### ISSUE THREAD

**Issue by hubbardmatthew** [UksusoFF/webtrees-tree_view_full_screen#2]
Hi, thanks for this module and the faces one.

I'm running version 2.0.3 of webtrees and v0.5 of your Tree View Full Screen module.

When I go to Charts -> Interactive Tree I get the full screen toggle and it works as expected.

When I go to an Individual page and then the Interactive Tree tab (as shown in the screenshot in your Readme) I don't get the full screen button.

Let me know if you need any more information.

**Comment by UksusoFF** [comment]
@hubbardmatthew 

Which webtrees theme you use? Any errors on [console panel](https://developers.google.com/web/tools/chrome-devtools/open)?

**Comment by hubbardmatthew** [comment]
Thanks for the quick response.

I'm running the base webtrees theme. I'm using this docker image https://github.com/NathanVaughn/webtrees-docker

The only error on console panel is 
`DevTools failed to parse SourceMap: https://mysite.tld/webtrees/public/js/vendor.min.js.map`
which seems to be on all webtrees pages.

I also get the same error on the page that works OK.

I've tried different browsers and pc and android, all with same result.

**Comment by hubbardmatthew** [comment]
Looks like it's something at my end. I just spun up a new docker image on a test server and it works.

**Comment by JLL76** [comment]
Hello
I note the same thing whatever the theme used.
In the individual page, there is no full screen button.
And also, this problem exists when displaying this diagram in the home page.
I use WT v2 and I really like this full screen diagram!
Thank you
JEAN-LUC
![Capture page individuelle bouton plein ecran](https://user-images.githubusercontent.com/65648013/84573284-e2851800-ad9f-11ea-9df1-e5ff5d3eb1c6.JPG)
![Capture arbre interactif bouton plein ecran](https://user-images.githubusercontent.com/65648013/84573287-e87af900-ad9f-11ea-90e9-63136c9e6745.JPG)

**Comment by UksusoFF** [comment]
@JLL76 which WT full version?

**Comment by JLL76** [comment]
I use WT 2.0.5 with additional modules (Webtree compact, REMINDER). The problem also existed with WT 2.0.4.

**Comment by UksusoFF** [comment]
Just updated to 2.0.5 and saw full screen on individuals page: https://tree.iamdrunk.ru/tree/jfk/individual/I8/Patrick-Joseph-Kennedy#tab-tree

On chart page it's disappear: https://tree.iamdrunk.ru/module/tree/Chart/jfk?xref=I8

You see any js error on individuals page? 
Chart page I will check asap.

**Comment by UksusoFF** [comment]
@JLL76 found why it's not work on you instance. It's because you install webtrees in subfolder.

**Comment by UksusoFF** [comment]
@JLL76 please check master version for fix.

**Comment by hubbardmatthew** [comment]
Thankyou, the fix in master is working for me. I'm also running webtrees in a subfolder so looks like that was my issue too.

Thanks, again.

**Comment by JLL76** [comment]
Yes, I notice that in your tree, it works well on different particular pages.
On the other hand, not being champion of the installation of WT in manual, the subfolder of WT, I do not know too well, because with each new version I pass in automatic.
Can you tell me more ?
thank you
J-LUC

**Comment by UksusoFF** [comment]
@JLL76 you cheking master version?

**Comment by JLL76** [comment]
It's OK for the master for the individual pages of my own tree!
But it doesn't work on the home page.
What can I do for the last problem?
Thank you


http://arbrelelievre.yj.fr/webtrees/index.php?route=%2Fwebtrees%2Ftree%2Ftree1

**Comment by UksusoFF** [comment]
I didn't know that chart can be on main page inside block :)

Fixed but have some issues. Wait some days please.

**Comment by UksusoFF** [comment]
@JLL76 check new version.

**Comment by JLL76** [comment]
575/5000
Hello
I summarize:
1- in "disconnection" mode it works perfectly (home page graphic, personal page and interactive tree diagram are OK)

2- in "connection" mode, 2 problems encountered:
- personal pages: the full page button only appears if I move the tree
-in all cases for the interactive tree, the little yellow character
  linked to the name no longer appears in the boxes (which is really useful because it allows easy navigation in the interactive tree)
attached a capture for this example
Thank you for this work which is progressing well!
Jean-Luc
![Capture v6 full screen deconnexion](https://user-images.githubusercontent.com/65648013/85512757-88cfe980-b5fa-11ea-8d2b-5567fd2d7710.JPG)
![Capture v6 full screen2 connexion](https://user-images.githubusercontent.com/65648013/85512761-89688000-b5fa-11ea-8ecd-501db2361b61.JPG)

**Comment by UksusoFF** [comment]
@JLL76 please create new issues for other problems :)
I see yellow person icon on your webtrees.

![image](https://user-images.githubusercontent.com/1931442/85515439-2ed91f00-b60e-11ea-8830-486079b5da2d.png)
