### ISSUE TITLE
Pb Yellow person icon V0.6

### ISSUE THREAD

**Issue by JLL76** [UksusoFF/webtrees-tree_view_full_screen#3]
386/5000
In "connected" mode, 2 problems encountered:

Personal pages: the full page button only appears if I move the tree structure.

In all cases for the interactive tree, yellow person icon linked to the name no longer appears in the boxes (which is really useful because it allows easy navigation in the tree interactivity) **and this only in online mode**.
Thank you
J-LUC

**Comment by UksusoFF** [comment]
> Personal pages: the full page button only appears if I move the tree structure.

Seems it something changed in webtrees. In 2.0.5 version it's work.

UPD: This commit break it: https://github.com/fisharebest/webtrees/commit/5675e46e95889fb28aff4062c093dba0f879e5f5

> In all cases for the interactive tree, yellow person icon linked to the name no longer appears in the boxes (which is really useful because it allows easy navigation in the tree interactivity) and this only in online mode.

Can you give me url where it's disappeared?
I still see it here: http://arbrelelievre.yj.fr/webtrees/index.php?route=%2Fwebtrees%2Ftree%2Ftree1

![image](https://user-images.githubusercontent.com/1931442/85515439-2ed91f00-b60e-11ea-8830-486079b5da2d.png)

**Comment by JLL76** [comment]
Yes it's OK without login !
But when I log into my account, the yellow icons disappear with this URL !
![Capture V6 FS PB ICONE PERSONNE](https://user-images.githubusercontent.com/65648013/85545270-16700100-b61c-11ea-9fc0-0818b0972665.JPG)

**Comment by UksusoFF** [comment]
Try to disable module. It's still disappear?
If true then you need search webtrees options for it - maybe it's permission issue.

**Comment by UksusoFF** [comment]
> Personal pages: the full page button only appears if I move the tree structure.

Should be fixed here: https://github.com/UksusoFF/webtrees-tree_view_full_screen/commit/710091c0ad19a09f71bf6416542ba2176dfe308a

**Comment by JLL76** [comment]
> Essayez de désactiver le module. C'est encore disparaître?
> Si vrai, vous avez besoin d'options de recherche sur Webtrees - c'est peut-être un problème de permission.


Yes, I think that's it!
I have not yet found for my account but for another user, it's OK

**Comment by JLL76** [comment]
> > Pages personnelles: le bouton pleine page n'apparaît que si je déplace l'arborescence.
> 
> Devrait être fixé ici: [710091c](https://github.com/UksusoFF/webtrees-tree_view_full_screen/commit/710091c0ad19a09f71bf6416542ba2176dfe308a)

After trying the V07, the diagram does not develop in full screen! on the other hand, in single screen mode, it works.

**Comment by UksusoFF** [comment]
Try to clear browser cache. Tested [here](http://arbrelelievre.yj.fr/webtrees/index.php?route=%2Fwebtrees%2Ftree%2Ftree1) and [here](http://arbrelelievre.yj.fr/webtrees/index.php?route=%2Fwebtrees%2Ftree%2Ftree1%2Findividual%2FI5%2FFRANCINE-LEONTINE-HERVIEUX#tab-tree).
Both works `¯\_(ツ)_/¯`

**Comment by JLL76** [comment]
I cleared the chrome browser cache, restart the computer, the problem on the full screen interactive tree: the tree does not develop when it is moved. I also tried on another computer: same problem.

**Comment by UksusoFF** [comment]
Ok. Understand what you mean. Will try to reproduce this on my trees.

**Comment by UksusoFF** [comment]
Please try it: https://github.com/UksusoFF/webtrees-tree_view_full_screen/commit/38732d49cf1e1dfa09fe51e62fd94bfc32ecc3a2
It's not load persons after expand but should load them after little drag.

**Comment by JLL76** [comment]
38732d4 For me, this version works very well!
I did not have an anomaly!
Thank you, it's great!
Jean-Luc
