### ISSUE TITLE
interactive tree with wt 2.0.16 anomaly

### ISSUE THREAD

**Issue by JLL76** [UksusoFF/webtrees-tree_view_full_screen#5]
If I use interactive tree by "chart" in the menu, the full screen view mixes with the top menu of wt and I cannot go back by that same button. On the other hand, the display works well by the interactive tree tab of the personal page ( the main menu can be removed by the scroll bar)
![Capture anomalie arbre inter wt 2-0-16](https://user-images.githubusercontent.com/65648013/117551321-968d3280-b045-11eb-8108-1cba42bc40d1.GIF)

**Comment by UksusoFF** [comment]
@JLL76 
On clean webtrees it's work: https://tree.iamdrunk.ru/module/tree/Chart/jfk?xref=I1

Seems you have https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf and conflict with it.

**Comment by JLL76** [comment]
In the meantime, there has been a new version of Vesta Current version: 2.0.16.0.4 (I was with Current version: 2.0.16.0.3). Conclusion, there was indeed a conflict with Vesta: now it's OK!
Thank you for your presence and response
JLL
