### ISSUE TITLE
Transparent Background with JustLight theme

### ISSUE THREAD

**Issue by nhrjr** [UksusoFF/webtrees-tree_view_full_screen#6]
Since updating to the latest version of the JustLight theme, there is no background of the tree view element in fullscreen mode anymore.
This means, that the website is still visible behind the elements of the tree view in fullscreen mode.

https://github.com/JustCarmen/webtrees-theme-justlight

**Comment by UksusoFF** [comment]
Fixed in https://github.com/UksusoFF/webtrees-tree_view_full_screen/commit/1fbb4d76d1094d78a53e30e1a8335021635f1cda
