### ISSUE TITLE
In the new version of webtrees the full screen fails

### ISSUE THREAD

**Issue by yako1984** [UksusoFF/webtrees-tree_view_full_screen#7]
In the new version of webtrees the full screen fails.
It is superimposed over the text of the web.

**Comment by UksusoFF** [comment]
Which version and theme you use?

**Comment by yako1984** [comment]
JustLight 2.1.1

**Comment by UksusoFF** [comment]
Webtrees version?

**Comment by yako1984** [comment]
website 2.0.19

**Comment by UksusoFF** [comment]
Tested on this version. All ok.
Seems this is same issue: https://github.com/UksusoFF/webtrees-tree_view_full_screen/issues/6
Try latest master version: https://github.com/UksusoFF/webtrees-tree_view_full_screen/archive/refs/heads/master.zip

**Comment by yako1984** [comment]
okay. I try it and tell you. I did not notice, why webtrees did not notify me of a new version in the module.

**Comment by yako1984** [comment]
Correct, since the last master version works correctly. Thank you for your work
